-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"), { description = "ghostty" })
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + Q")
hl.unbind("SUPER + T")
hl.unbind("SUPER + space")
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.close(), { description = "Close window" })
